services:
  - type: web
    name: atm-banking-system
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.app.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: atm-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.0

databases:
  - name: atm-db
    databaseName: atm_db
    user: db_user
